- name: Get and report patches installed yesterday with HTML report
  hosts: Linux
  become: yes
  vars:
    report_path: /tmp/patch_report_yesterday.html

  tasks:
    - name: Define yesterday's date string
      set_fact:
        yesterday_date: "{{ lookup('pipe', 'date --date=\"yesterday\" \'+%d %b %Y\'') }}"

    - name: Get list of installed patches with install dates
      command: rpm -qa --last
      register: rpm_list

    - name: Filter packages installed yesterday
      set_fact:
        patches_yesterday: "{{ rpm_list.stdout_lines | select('search', yesterday_date) | list }}"

    - name: Generate HTML report content
      set_fact:
        html_content: |
          <html>
          <head><title>Patch Report for {{ yesterday_date }}</title></head>
          <body>
            <h1>Installed Patches on {{ yesterday_date }}</h1>
            {% if patches_yesterday | length > 0 %}
              <ul>
              {% for patch in patches_yesterday %}
                <li>{{ patch }}</li>
              {% endfor %}
              </ul>
            {% else %}
              <p>No patches installed on {{ yesterday_date }}.</p>
            {% endif %}
          </body>
          </html>

    - name: Write HTML report to file on remote server
      copy:
        content: "{{ html_content }}"
        dest: "{{ report_path }}"
        mode: '0644'

    - name: Show report location
      debug:
        msg: "HTML patch report generated at {{ report_path }}"
