- name: Template Summary Report
  ansible.builtin.template:
    src: "scan_reports.html.j2"
    dest: "{{ file_path }}/linuxsummary/index.html"
    owner: root
    group: root
    mode: '0644'
  delegate_to: 172.25.225.97
  run_once: true

- name: DISPLAY LINK TO SUMMARY REPORT
  ansible.builtin.debug:
    msg: "http://172.25.225.97/openscap/linuxsummary/"
  run_once: true

- name: Template Summary Report for e-mail
  ansible.builtin.template:
    src: "scan_reports.html.j2"
    dest: "/tmp/linux{{ ansible_date_time.iso8601 }}.html"
    owner: root
    group: root
    mode: '0644'
  delegate_to: localhost
  run_once: true
  when: sendemailreport

- name: Find all scap folders
  ansible.builtin.find:
    paths: /var/www/html/openscap
    file_type: directory
  delegate_to: 172.25.225.97
  run_once: true
  register: completedreports

- name: Create Scap Report Index Page
  ansible.builtin.template:
    src: "indexpage.html.j2"
    dest: "{{ file_path }}/index.html"
    owner: root
    group: root
    mode: '0644'
  delegate_to: report.shadowman.dev
  run_once: true

- name: DISPLAY LINK TO SUMMARY REPORT
  ansible.builtin.debug:
    msg: "https://172.25.225.97/openscap/index.html"
  run_once: true
