---
- name: Get and report patches installed yesterday with HTML report
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    report_path: "/tmp/patch_report.html"

  tasks:

    - name: Define yesterday's date string
      set_fact:
        yesterday: "{{ lookup('pipe', 'date --date=\"yesterday\" \"+%d %b %Y\"') }}"

    - name: Get list of packages installed yesterday
      shell: "rpm -qa --last | grep '{{ yesterday }}'"
      register: installed_yesterday
      changed_when: false

    - name: Format HTML report
      copy:
        dest: "{{ report_path }}"
        content: |
          <html>
          <head><title>Patch Report - {{ inventory_hostname }}</title></head>
          <body>
          <h1>Patch Report for {{ inventory_hostname }}</h1>
          <h2>Date: {{ yesterday }}</h2>
          <pre>
          {% if installed_yesterday.stdout %}
          {{ installed_yesterday.stdout }}
          {% else %}
          No packages installed on {{ yesterday }}.
          {% endif %}
          </pre>
          </body>
          </html>

    - name: Display path to HTML report
      debug:
        msg: "HTML patch report saved to {{ report_path }}"

